spring:
  redis:
    database: 0
    host: 192.168.88.88
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 60
        min-idle: 1
    timeout: 10000
    password: foobar
#  security:
#    user:
#      password: 000000